In [37]:
# Import library
from vaderSentiment.vaderSentiment import SentimentIntensityAnalyzer 
import pandas as pd
from transformers import pipeline

#### Load the Datasets

In [ ]:
# Read the csv file
teaser = pd.read_csv("./data/teaser_comments.csv")


test = teaser[:1000]

In [46]:
analyzer = SentimentIntensityAnalyzer()

def get_vader_scores(text):
    scores = analyzer.polarity_scores(text)
    print("Text", text, "Score", scores)

    return scores["neg"], scores["neu"], scores["pos"], scores["compound"]

def get_vader_label(compound):
    if compound >= 0.05:
        return "positive"
    elif compound <= -0.05:
        return "negative"
    else:
        return "neutral"

In [47]:
for text in test["text"]:
    vader_scores = get_vader_scores(text)
    vader_label = get_vader_label(vader_scores[3])
    test["vader_sentiment"] = vader_label
    test["vader_compound"] = vader_scores[3]

test.head(20)

Text Le sserafim motomamiiiiis Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text <b>INDUSTRY TAKEOVER</b> Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text slayyy Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text we gonna wait another day for teaser 2 t-t I&#39;m so hyped!!! Score {'neg': 0.207, 'neu': 0.793, 'pos': 0.0, 'compound': -0.4359}
Text わしはルセラフィムを応援し続ける覚悟があります Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text pusing cakep-cakep mereka T__T Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text KECEEE KECEEE ABIS!! Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text keceee bgt woi Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text <a href="https://www.youtube.com/watch?v=A4twVWwOueU&amp;t=8">0:08</a> whats her name?? Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Bighits gonna surprise us again ✨ Score {'neg': 0.0, 'neu': 0.476, 'pos': 0.524, 'compound': 0.5267}
Text Can&#39;t wait for it ^^ Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text I LITERALLY CANT WAIT AHAHAHAHSHUS DISKSJS Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Si quieren lograr que las vistas suban por favor no postee el vídeo completo a plataformas como Twitter.... La gente lo ve ahí y ya no viene a YouTube. Solo suba una imagen y deje el enlace oficial, así la gente vendrá directo al video aquí!! <br>Haganlo bien por favor! Fighting 🌸 Score {'neg': 0.127, 'neu': 0.785, 'pos': 0.088, 'compound': -0.3348}
Text AHHHH HERE TO WITNESS THEM DEBUT Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text SCREAMINGGGGGG Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Sakuraaaaaa!!!!!! I&#39;m so excited Score {'neg': 0.0, 'neu': 0.412, 'pos': 0.588, 'compound': 0.6468}
Text purrrr Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Son todas unas motomamis! Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Wow, este teaser sí que genera curisosidad sobre la canción. Score {'neg': 0.145, 'neu': 0.58, 'pos': 0.275, 'compound': 0.4215}
Text Cool girls Score {'neg': 0.0, 'neu': 0.303, 'pos': 0.697, 'compound': 0.3182}
Text 맙소사 나는 이미 이것을 좋아했습니다!!! Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Sakura in the first part was fire🔥🔥🔥🔥🔥and the chore gonna be lit Score {'neg': 0.5, 'neu': 0.5, 'pos': 0.0, 'compound': -0.875}
Text IM SO EXCITED Score {'neg': 0.0, 'neu': 0.426, 'pos': 0.574, 'compound': 0.4005}
Text <a href="https://www.youtube.com/watch?v=A4twVWwOueU&amp;t=3">00:03</a> I like the Cat Helmet, where can I get that? Score {'neg': 0.0, 'neu': 0.794, 'pos': 0.206, 'compound': 0.4329}
Text Six Seraphim are descending to rule our hearts! Score {'neg': 0.0, 'neu': 0.604, 'pos': 0.396, 'compound': 0.68}
Text the last scene  reminds me of the new gg h1key Score {'neg': 0.0, 'neu': 0.804, 'pos': 0.196, 'compound': 0.296}
Text I can&#39;t stop watch this 🤩 Score {'neg': 0.306, 'neu': 0.694, 'pos': 0.0, 'compound': -0.296}
Text THIS LOOKS SO COOL I&#39;M OVER THE MOON Score {'neg': 0.0, 'neu': 0.701, 'pos': 0.299, 'compound': 0.4572}
Text sakura omgg Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Ese casco de la Motomami 😝 Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text 最高です Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Ooooh they look cool! I like it! Score {'neg': 0.0, 'neu': 0.482, 'pos': 0.518, 'compound': 0.658}
Text finally !!!! Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text This is so hype and hot omggg Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text 🫣🫣🫣 Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text LESSERAFIM IS FEARLESS!!! THEY ARE SO HOT!!! 🔥 🔥 🔥😍😍😍😍 Score {'neg': 0.207, 'neu': 0.41, 'pos': 0.383, 'compound': 0.8273}
Text Mbak DP Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Amo Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Omg Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Ga sabar lagi!! Keren!! 😭😭 Cant waittt!!!!?!! Sakuraaa saranghae!!🌸🌸 Score {'neg': 0.315, 'neu': 0.685, 'pos': 0.0, 'compound': -0.811}
Text Y si, aún no debutan, este solo 17 segundos en un teaser y yo ya quiero comeback!!<br>LE SSERAFIM será el primer girl group que apoyaré y ya las amoo!!<br>Su álbum completo es arte y la single principal viene con todo!💜 Score {'neg': 0.089, 'neu': 0.823, 'pos': 0.089, 'compound': 0.4885}
Text これは絶対かっこいいやつー🥹💓💓 Score {'neg': 0.178, 'neu': 0.059, 'pos': 0.763, 'compound': 0.8979}
Text Fearless girls will officially make their debut on Monday&lt;3 Score {'neg': 0.0, 'neu': 0.734, 'pos': 0.266, 'compound': 0.4404}
Text LE SSERAFIM = IM FEARLESS 😮 i just noticed Score {'neg': 0.0, 'neu': 0.752, 'pos': 0.248, 'compound': 0.5622}
Text LE SSERAFIM is gonna rule this world! FEARLESS is a bop! Can&#39;t wait for their debut. Score {'neg': 0.0, 'neu': 0.781, 'pos': 0.219, 'compound': 0.639}
Text Uh oh😁 Score {'neg': 0.0, 'neu': 0.667, 'pos': 0.333, 'compound': 0.4588}
Text Aespa next level Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text CHAEWON dios están bueno Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text They are gonna end careers dang Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text 채원님이다 ㅠㅠ Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Idk why people saying this is too short like I get it is short, but do you expect it to be like a minute long lol,  well that’s why it’s called a teaser.<br>We’re getting another teaser as well and their debut is not far away Score {'neg': 0.066, 'neu': 0.682, 'pos': 0.251, 'compound': 0.8834}
Text แชร์อะไรก็ไม่น่ารักเท่าแชวอนของเรา  กิ้งๆ Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text tambah ga sabar😶 Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Nunggu lebaran + nunggu MV Release Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Oh the girlies are eating! I’m ready Score {'neg': 0.0, 'neu': 0.682, 'pos': 0.318, 'compound': 0.4199}
Text This teaser teased us alot, too short and captivating..i&#39;m excited to watch full ver. Score {'neg': 0.239, 'neu': 0.625, 'pos': 0.136, 'compound': -0.2023}
Text Play - Pause - Repeat again and again😅😅 Score {'neg': 0.0, 'neu': 0.637, 'pos': 0.363, 'compound': 0.7506}
Text Tiene potencial Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text IM FEARLESS 😩😵‍💫 Score {'neg': 0.471, 'neu': 0.239, 'pos': 0.29, 'compound': -0.0688}
Text At <a href="https://www.youtube.com/watch?v=A4twVWwOueU&amp;t=9">0:09</a> its the same move that Garam did in her introduction video! (<a href="https://www.youtube.com/watch?v=A4twVWwOueU&amp;t=12">0:12</a>) Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text En espera de su debut🥰❤ Score {'neg': 0.0, 'neu': 0.439, 'pos': 0.561, 'compound': 0.91}
Text TRUE FACT: LE SSERAFIM INVENTED MOTOMAMI CONCEPT Score {'neg': 0.0, 'neu': 0.682, 'pos': 0.318, 'compound': 0.4215}
Text divas que vão servir muito Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text ESTAMOS A NADA Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Queens lesserafim Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text HERMOSASS Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text I just realized that their logo  is like wings  stands for le seraphim  angels!! Score {'neg': 0.0, 'neu': 0.808, 'pos': 0.192, 'compound': 0.4738}
Text LENDAS Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Omg ya quiero verlo!! Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text teaser nya aja udah keren woiii. gila Score {'neg': 0.25, 'neu': 0.75, 'pos': 0.0, 'compound': -0.25}
Text Geweldig om dit te zien top 👍👍👍👍 Score {'neg': 0.0, 'neu': 0.878, 'pos': 0.122, 'compound': 0.2023}
Text Sakuraaaaaaaaaa🥺🥺🥺🥺🥺 Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text さくらちゃん🥹❤️❤️❤️ Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text They way this bop is calming and yet catchy, it’s only LE SSERAFIM!!! Score {'neg': 0.0, 'neu': 0.77, 'pos': 0.23, 'compound': 0.5538}
Text I can&#39;t wait any lonngggerrr Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text MAY 2 PLS COME FASTERRRR Score {'neg': 0.0, 'neu': 0.663, 'pos': 0.337, 'compound': 0.2577}
Text it has a catchy tone . I like it a lot Score {'neg': 0.0, 'neu': 0.8, 'pos': 0.2, 'compound': 0.3612}
Text They’re so fineeee can’t wait for the debut Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text I&#39;m so hyped for their debut 🌺🌺 Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text I need more ;; Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Estou tão ansiosa Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Chega logo dia 2 Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Lesserafim fighting Score {'neg': 0.714, 'neu': 0.286, 'pos': 0.0, 'compound': -0.3612}
Text Esperando el debut de las serafínas! Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text ahhh gak seru ada KANG BULLY Score {'neg': 0.44, 'neu': 0.56, 'pos': 0.0, 'compound': -0.6037}
Text Let&#39;s reach our 2 million goal Score {'neg': 0.0, 'neu': 0.82, 'pos': 0.18, 'compound': 0.0258}
Text este debut es el que me causa más curiosidad y emoción todas se ven increíbles ❤ Score {'neg': 0.0, 'neu': 0.792, 'pos': 0.208, 'compound': 0.6369}
Text Garam Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text They will eat Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text No puedo esperar Dios, Le Sserafim va a romperla Score {'neg': 0.216, 'neu': 0.784, 'pos': 0.0, 'compound': -0.296}
Text So exciteddd Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Wow sakura, i&#39;am speechless.... Score {'neg': 0.0, 'neu': 0.441, 'pos': 0.559, 'compound': 0.5859}
Text I like the transitions in the teaser, showing the choreo bit at the end. The small sound we heard is getting me pumped! It&#39;s like one of those sounds that makes you want to go, go, go and get work done! And the vibe of the teaser is giving me that exact sentiment, too! Score {'neg': 0.065, 'neu': 0.78, 'pos': 0.156, 'compound': 0.6784}
Text AHHHHHHHH Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text I am waiting for their debut Le sserrafim Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Commenting for yt algorithm Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Ooooooh, this looks amazing!!! Score {'neg': 0.0, 'neu': 0.391, 'pos': 0.609, 'compound': 0.6884}
Text YAAAAASSS Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text DAMNN Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text 💗 Score {'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound': 0.7096}
Text im looking forward to watching the mv Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text looks pretty cool Score {'neg': 0.0, 'neu': 0.154, 'pos': 0.846, 'compound': 0.6705}
Text Me encanta cuando dicen el nombre del grupo xd Score {'neg': 0.0, 'neu': 0.678, 'pos': 0.322, 'compound': 0.5859}
Text 最後のチェウォンにやられた… Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Wow estoy muy emocionadaa, fan desde antes del debut ❤ Score {'neg': 0.0, 'neu': 0.437, 'pos': 0.563, 'compound': 0.8834}
Text Me encanta pero no pude ir evitar cantar motomami xd Score {'neg': 0.157, 'neu': 0.571, 'pos': 0.271, 'compound': 0.3818}
Text واوز Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Waaaaaaaaaaaaaaa can&#39;t waittt ahhhhhh lesserafimmmm fighting!!!<br>Btw what&#39;s the fandom name :))) Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text YASSS Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text feeling that this will be yunjin’s era Score {'neg': 0.0, 'neu': 0.8, 'pos': 0.2, 'compound': 0.128}
Text Im so excited for their debut !! Score {'neg': 0.0, 'neu': 0.647, 'pos': 0.353, 'compound': 0.5068}
Text predebut fan here Score {'neg': 0.0, 'neu': 0.465, 'pos': 0.535, 'compound': 0.3182}
Text Aku bakalan suka lagunya!! <br><br>Kenapa ya artis selain bh vi3wsnya pada cepat sedangkan artis bh sendiri kaya frezee Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text É A PORRA DA CHAEWON! Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Mv güzel gibi umarım istediğim gibi olur.pek anlayamadim Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text LE-SSERAFIM= GORGEOUSLY TALENTED 😍 Score {'neg': 0.0, 'neu': 0.265, 'pos': 0.735, 'compound': 0.9015}
Text Wow! Score {'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound': 0.6239}
Text Can already tell Yunjin gonna be a bias Score {'neg': 0.167, 'neu': 0.833, 'pos': 0.0, 'compound': -0.1027}
Text tô ansiosaaaaaa 💗 Score {'neg': 0.0, 'neu': 0.253, 'pos': 0.747, 'compound': 0.7096}
Text Let&#39;s str...m in correct way Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text AH ESTAN BUENO Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text We need to get our streaming machines hopefully we can achieve our goals 🙌 Score {'neg': 0.0, 'neu': 0.838, 'pos': 0.162, 'compound': 0.4019}
Text Sakura chaaannnn! Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Lesserafim motomamis Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text ปังมาก Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Bitin po Score {'neg': 0.783, 'neu': 0.217, 'pos': 0.0, 'compound': -0.5574}
Text dayyyuuummm interestinggggg teasserrrrrrrrr Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Omg Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text AAAAHHHHHHHH I can’t wait to see Chaewon back in action 😭😭😭😭 Score {'neg': 0.408, 'neu': 0.592, 'pos': 0.0, 'compound': -0.9081}
Text OMG can&#39;t wait Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text OMG Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Gran teaser! Score {'neg': 0.696, 'neu': 0.304, 'pos': 0.0, 'compound': -0.3164}
Text Quality ganna be insaaaaane... Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text This girl group gonna be QUEENS of kpop. Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text 500k+ view in jst 4hrs???? I&#39;M SO PROUD OF MY GIRLS Score {'neg': 0.0, 'neu': 0.596, 'pos': 0.404, 'compound': 0.8309}
Text :3 Score {'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound': 0.5106}
Text Omggg Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text This is gonna be my fav girl group Score {'neg': 0.0, 'neu': 0.7, 'pos': 0.3, 'compound': 0.4588}
Text four more days until FEARLESS Score {'neg': 0.0, 'neu': 0.507, 'pos': 0.493, 'compound': 0.5989}
Text So excited Score {'neg': 0.0, 'neu': 0.271, 'pos': 0.729, 'compound': 0.4005}
Text 😂😂😂😂😂😂😂당신은 무엇을 가지고 있습니까, 하나님,이란의 모든 자녀는 당신의 팬입니다 Score {'neg': 0.201, 'neu': 0.454, 'pos': 0.345, 'compound': 0.9382}
Text omgggg vem aí Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Это слишком прекрасно!! Как визуан, я безумно рада за девочек 😭 Score {'neg': 0.235, 'neu': 0.765, 'pos': 0.0, 'compound': -0.5696}
Text مااااعرف يههههبلون بكل معنى الكلمه Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Nao tem som mesmo ou eu é q tou sem som?<br>.<br>It does not have sound or is my phone? Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text ساكورا يممممه تهبل😭 Score {'neg': 0.383, 'neu': 0.617, 'pos': 0.0, 'compound': -0.4767}
Text كلهم يجنننننوننن Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text they didnt come here to play they came to slay Score {'neg': 0.0, 'neu': 0.789, 'pos': 0.211, 'compound': 0.34}
Text طبيعي شفته اكتر من مره؟؟؟ Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text يمممممه!!!!!!ايش ذااااا Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text اوب Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text 楽しみ！ Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text AAA IM SO WXCITED Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Interesting! Score {'neg': 0.0, 'neu': 0.0, 'pos': 1.0, 'compound': 0.4574}
Text <b>KIM GARAM SUPREMACY!!!</b> Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text let&#39;s go Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text cok merak ettim of Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Я В ВОСТОРГЕ!! ХОЧУ ДЕБЮТ УЖЕЕЕ Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text kisa sacli kiz ates ediyor 💥💥 Score {'neg': 0.5, 'neu': 0.5, 'pos': 0.0, 'compound': -0.6124}
Text wow I can&#39;t  wait  for  thier  comeback Score {'neg': 0.0, 'neu': 0.612, 'pos': 0.388, 'compound': 0.5859}
Text I’m a fan already Score {'neg': 0.0, 'neu': 0.566, 'pos': 0.434, 'compound': 0.3182}
Text I HONESTLY CANT WAIT Score {'neg': 0.0, 'neu': 0.5, 'pos': 0.5, 'compound': 0.4588}
Text Can&#39;t deny that I&#39;m really excited now. Score {'neg': 0.238, 'neu': 0.495, 'pos': 0.267, 'compound': 0.0754}
Text Roty Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Roty Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Toty Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Roty Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Roty Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Roty Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Can’t wait🥰 Score {'neg': 0.0, 'neu': 0.407, 'pos': 0.593, 'compound': 0.8074}
Text ROTY Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text ROTY Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Motomami? Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text I CAN FEEL IT..THEY ARE GOING TO OUT DO EVERY GIRL GROUP Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Damnnnn Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Looking forward to their debut Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text hybe sonubda 2dyzgun bı sey  yapabılmıs Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Omg Garam , go queen!!!! Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Le teaser. Score {'neg': 0.667, 'neu': 0.333, 'pos': 0.0, 'compound': -0.25}
Text le sserafim Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text BRAZIL ALREADY LOVES THIS GROUP! Score {'neg': 0.0, 'neu': 0.501, 'pos': 0.499, 'compound': 0.6114}
Text I&#39;M WAITING Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text ES MI FAV Y AÚN NO SALE Score {'neg': 0.216, 'neu': 0.49, 'pos': 0.294, 'compound': 0.2023}
Text NO PUEDO ESPERAR MAS 💖💖💖 Score {'neg': 0.117, 'neu': 0.119, 'pos': 0.764, 'compound': 0.9457}
Text each and every single one of them is standing out that’s what i love about le sserafim Score {'neg': 0.0, 'neu': 0.792, 'pos': 0.208, 'compound': 0.6369}
Text por un momento pensé que Garam era chaeryoung de itzy Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text omg Sakura Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Motomami motomami Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text Too short omg omg Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text You need to know Hybe never give us enough hints! Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text OMGGGGG I CAN&#39;T WAITTT Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text looking forward to them! Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text OMG Score {'neg': 0.0, 'neu': 1.0, 'pos': 0.0, 'compound': 0.0}
Text reminds me of a gorillaz song 🧐🧐🙃🙃😅 Score {'neg': 0.0, 'neu': 0.884, 'pos': 0.116, 'compound': 0.3612}

/var/folders/fq/8n_l7j9x6h9gn6knnd4lk4080000gn/T/ipykernel_1587/682190730.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["vader_sentiment"] = vader_label
/var/folders/fq/8n_l7j9x6h9gn6knnd4lk4080000gn/T/ipykernel_1587/682190730.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  test["vader_compound"] = vader_scores[3]

,group,video_id,publishedAt,author,text,likeCount,vader_sentiment,vader_compound
0,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:59:48Z,@MeelyBieber,Le sserafim motomamiiiiis,0,neutral,0.0
1,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:58:54Z,@allygarska,<b>INDUSTRY TAKEOVER</b>,1,neutral,0.0
2,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:58:04Z,@naswacitrarevalina6716,slayyy,1,neutral,0.0
3,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:56:06Z,@venvop9674,we gonna wait another day for teaser 2 t-t I&#...,3,neutral,0.0
4,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:55:45Z,@mess_mess_mess,わしはルセラフィムを応援し続ける覚悟があります,4,neutral,0.0
5,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:54:32Z,@zhamiradaffaandytra8185,pusing cakep-cakep mereka T__T,2,neutral,0.0
6,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:52:11Z,@vwiinterrb,KECEEE KECEEE ABIS!!,2,neutral,0.0
7,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:51:53Z,@vwiinterrb,keceee bgt woi,2,neutral,0.0
8,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:50:55Z,@soulmateofseulgi,"<a href=""https://www.youtube.com/watch?v=A4twV...",0,neutral,0.0
9,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:49:47Z,@Problematicbaka,Bighits gonna surprise us again ✨,0,neutral,0.0
10,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:49:00Z,@feellikeacinderellanegabye9710,Can&#39;t wait for it ^^,0,neutral,0.0
11,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:48:21Z,@strawbunny0338,I LITERALLY CANT WAIT AHAHAHAHSHUS DISKSJS,0,neutral,0.0
12,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:47:24Z,@mireYANG97,Si quieren lograr que las vistas suban por fav...,1,neutral,0.0
13,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:46:47Z,@pshev,AHHHH HERE TO WITNESS THEM DEBUT,0,neutral,0.0
14,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:46:34Z,@pshev,SCREAMINGGGGGG,0,neutral,0.0
15,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:45:55Z,@justincapon494,Sakuraaaaaa!!!!!! I&#39;m so excited,0,neutral,0.0
16,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:44:18Z,@jaylee7132,purrrr,0,neutral,0.0
17,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:43:56Z,@Garsaland,Son todas unas motomamis!,0,neutral,0.0
18,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:43:52Z,@vicsw08,"Wow, este teaser sí que genera curisosidad sob...",0,neutral,0.0
19,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:41:24Z,@aiyuikimkkura6813,Cool girls,0,neutral,0.0

In [43]:
sentiment_model = pipeline(
    "sentiment-analysis",
    model="cardiffnlp/twitter-roberta-base-sentiment-latest"
)

def roberta_sentiment(text):
    if not isinstance(text, str) or text.strip() == "":
        return {"label": "neutral", "score": 0}

    result = sentiment_model(text[:512])
    return result

Some weights of the model checkpoint at cardiffnlp/twitter-roberta-base-sentiment-latest were not used when initializing RobertaForSequenceClassification: ['roberta.pooler.dense.bias', 'roberta.pooler.dense.weight']
- This IS expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing RobertaForSequenceClassification from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).
Device set to use mps:0

In [44]:
roberta_test = test.copy()

for text in roberta_test["text"]:
    result = roberta_sentiment(text)
    roberta_test["roberta_sentiment"] = result[0]["label"]
    roberta_test["roberta_confidence"] = result[0]["score"]

roberta_test.head(20)

,group,video_id,publishedAt,author,text,likeCount,vader_sentiment,vader_compound,roberta_sentiment,roberta_confidence
0,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:59:48Z,@MeelyBieber,Le sserafim motomamiiiiis,0,neutral,0.0,positive,0.973222
1,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:58:54Z,@allygarska,<b>INDUSTRY TAKEOVER</b>,1,neutral,0.0,positive,0.973222
2,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:58:04Z,@naswacitrarevalina6716,slayyy,1,neutral,0.0,positive,0.973222
3,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:56:06Z,@venvop9674,we gonna wait another day for teaser 2 t-t I&#...,3,neutral,0.0,positive,0.973222
4,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:55:45Z,@mess_mess_mess,わしはルセラフィムを応援し続ける覚悟があります,4,neutral,0.0,positive,0.973222
5,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:54:32Z,@zhamiradaffaandytra8185,pusing cakep-cakep mereka T__T,2,neutral,0.0,positive,0.973222
6,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:52:11Z,@vwiinterrb,KECEEE KECEEE ABIS!!,2,neutral,0.0,positive,0.973222
7,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:51:53Z,@vwiinterrb,keceee bgt woi,2,neutral,0.0,positive,0.973222
8,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:50:55Z,@soulmateofseulgi,"<a href=""https://www.youtube.com/watch?v=A4twV...",0,neutral,0.0,positive,0.973222
9,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:49:47Z,@Problematicbaka,Bighits gonna surprise us again ✨,0,neutral,0.0,positive,0.973222
10,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:49:00Z,@feellikeacinderellanegabye9710,Can&#39;t wait for it ^^,0,neutral,0.0,positive,0.973222
11,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:48:21Z,@strawbunny0338,I LITERALLY CANT WAIT AHAHAHAHSHUS DISKSJS,0,neutral,0.0,positive,0.973222
12,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:47:24Z,@mireYANG97,Si quieren lograr que las vistas suban por fav...,1,neutral,0.0,positive,0.973222
13,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:46:47Z,@pshev,AHHHH HERE TO WITNESS THEM DEBUT,0,neutral,0.0,positive,0.973222
14,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:46:34Z,@pshev,SCREAMINGGGGGG,0,neutral,0.0,positive,0.973222
15,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:45:55Z,@justincapon494,Sakuraaaaaa!!!!!! I&#39;m so excited,0,neutral,0.0,positive,0.973222
16,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:44:18Z,@jaylee7132,purrrr,0,neutral,0.0,positive,0.973222
17,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:43:56Z,@Garsaland,Son todas unas motomamis!,0,neutral,0.0,positive,0.973222
18,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:43:52Z,@vicsw08,"Wow, este teaser sí que genera curisosidad sob...",0,neutral,0.0,positive,0.973222
19,LE SSERAFIM,A4twVWwOueU,2022-04-28T20:41:24Z,@aiyuikimkkura6813,Cool girls,0,neutral,0.0,positive,0.973222

In [45]:
print(roberta_test["roberta_sentiment"].value_counts())
print(roberta_test["roberta_confidence"].median())

roberta_sentiment
positive    1000
Name: count, dtype: int64
0.9732216596603394